version: '3'
services:
  api-tg:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: api-tg
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    networks:
      - api-tg

networks:
  api-tg:
