version: '3'
services:
  api-postgres:
    image: postgres:14
    container_name: api_postgres
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-redis:
    image: redis
    container_name: api-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
