version: '3'

services:
  api-tg:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: api-tg
    depends_on:
      - api-postgres
      - api-redis
    ports:
      - "9000:80"
    environment:
      - DYNACONF_DATABASE_URL="postgresql://postgres:123qwe@api-postgres:5432/postgres"
      - DYNACONF_REDIS_URL="redis://:@api-redis:6379/0"
    networks:
      - api-tg

  api-postgres:
    image: postgres:14
    container_name: api_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api-tg

  api-redis:
    image: redis
    container_name: api-redis
    ports:
      - "6379:6379"
    networks:
      - api-tg

networks:
  api-tg:
